INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = messagehook

messagehook_FILES = Tweak.x
messagehook_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
